### ISSUE TITLE
no maccro rules for tuples with types as closure arguments 

### ISSUE THREAD

**Issue by rajasekarv** [alecmocatta/serde_closure#7]
Thanks for this wonderful library. I am dealing with generic closure like this.
```
Fn(T) -> U
```
Therefore I can only use tuples as closure argument. When types are inferred there is no problem with Fn! macro. But when I have to provide type annotations, it is not compiling. 
```
let f = Fn!(|(x, y): (i32, i32)| -> (String, i32) { ((x + 2).to_string(), y + 2) });
```
Can you please provide some solutions? It would be really helpful for me.

**Comment by alecmocatta** [comment]
Sorry for the slow response @rajasekarv!

I hope to improve these macros in future to handle destructuring arguments, but in the meantime this should work:

```rust
let f = Fn!(|x: (i32, i32)| -> (String, i32) {
    let (x, y) = x;
    ((x + 2).to_string(), y + 2)
});
```

 I'm not able to test this at the moment, so do let me know if you encounter any further issues.

**Comment by rajasekarv** [comment]
This solves the problem of having to write functions every time. This library is extremely useful in distributed computing. Thanks a lot for publishing this.
